In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('used_car_listings_13_12_2025.csv')

In [3]:
df.head()

,year,manufacturer,fuelType,name,transmission,engine,mileage,listingPrice,variant,age
0,2013.0,Toyota,Hybrid,Toyota Prius 2013 for sale in Karachi,Automatic,1800cc,"156,000 km",4125000.0,Prius,12.0
1,2008.0,Toyota,Petrol,Toyota Vitz 2008 for sale in Karachi,Automatic,1000cc,"85,000 km",2080000.0,Vitz,17.0
2,2022.0,Daihatsu,Petrol,Daihatsu Mira 2022 for sale in Karachi,Automatic,660cc,"16,000 km",3575000.0,Mira,3.0
3,2022.0,Toyota,Petrol,Toyota Passo 2022 for sale in Karachi,Automatic,1000cc,"68,000 km",3990000.0,Passo,3.0
4,2013.0,Honda,Hybrid,Honda Insight 2013 for sale in Karachi,Automatic,1300cc,"78,000 km",2890000.0,Insight,12.0

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15171 entries, 0 to 15170
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   year          15171 non-null  float64
 1   manufacturer  15171 non-null  str
 2   fuelType      15171 non-null  str
 3   name          15171 non-null  str
 4   transmission  15171 non-null  str
 5   engine        15171 non-null  str
 6   mileage       15171 non-null  str
 7   listingPrice  15171 non-null  float64
 8   variant       15171 non-null  str
 9   age           15171 non-null  float64
dtypes: float64(3), str(7)
memory usage: 1.2 MB

In [5]:
df.describe()

               year  listingPrice           age
count  15171.000000  1.517100e+04  15171.000000
mean    2014.120823  5.271934e+06     10.879177
std        8.798385  8.277969e+06      8.798385
min     1951.000000  1.040000e+05      0.000000
25%     2009.000000  1.600000e+06      4.000000
50%     2017.000000  3.200000e+06      8.000000
75%     2021.000000  5.650000e+06     16.000000
max     2025.000000  1.450000e+08     74.000000

In [6]:
df.duplicated().sum()

np.int64(2477)

In [7]:
df.duplicated(keep=False).sum()

np.int64(4911)

In [10]:
df[df.duplicated(keep=False)].sort_values(by=['manufacturer','variant','year',
                                              'mileage']).head(10)

,year,manufacturer,fuelType,name,transmission,engine,mileage,listingPrice,variant,age
1935,2018.0,Audi,Petrol,Audi A3 2018 for sale in Karachi,Automatic,1200cc,"45,812 km",8500000.0,A3,7.0
2017,2018.0,Audi,Petrol,Audi A3 2018 for sale in Karachi,Automatic,1200cc,"45,812 km",8500000.0,A3,7.0
4840,2018.0,Audi,Petrol,Audi A3 2018 for sale in Karachi,Automatic,1200cc,"92,000 km",6535000.0,A3,7.0
4958,2018.0,Audi,Petrol,Audi A3 2018 for sale in Karachi,Automatic,1200cc,"92,000 km",6535000.0,A3,7.0
3843,2019.0,Audi,Petrol,Audi A3 2019 for sale in Karachi,Automatic,1200cc,"43,359 km",6900000.0,A3,6.0
3901,2019.0,Audi,Petrol,Audi A3 2019 for sale in Karachi,Automatic,1200cc,"43,359 km",6900000.0,A3,6.0
4630,2012.0,Audi,Petrol,Audi A4 2012 for sale in Karachi,Automatic,1800cc,"39,785 km",7500000.0,A4,13.0
4641,2012.0,Audi,Petrol,Audi A4 2012 for sale in Karachi,Automatic,1800cc,"39,785 km",7500000.0,A4,13.0
263,2014.0,Audi,Petrol,Audi A4 2014 for sale in Karachi,Automatic,1800cc,"48,000 km",6500000.0,A4,11.0
312,2014.0,Audi,Petrol,Audi A4 2014 for sale in Karachi,Automatic,1800cc,"48,000 km",6500000.0,A4,11.0

In [8]:
cols = ['manufacturer','variant','year','mileage','listingPrice']

In [9]:
df[df.duplicated(keep=False)].sort_values(by=['manufacturer','variant','year','mileage',
                                              'listingPrice'])[cols].head(20)

     manufacturer variant    year     mileage  listingPrice
1935         Audi      A3  2018.0   45,812 km     8500000.0
2017         Audi      A3  2018.0   45,812 km     8500000.0
4840         Audi      A3  2018.0   92,000 km     6535000.0
4958         Audi      A3  2018.0   92,000 km     6535000.0
3843         Audi      A3  2019.0   43,359 km     6900000.0
3901         Audi      A3  2019.0   43,359 km     6900000.0
4630         Audi      A4  2012.0   39,785 km     7500000.0
4641         Audi      A4  2012.0   39,785 km     7500000.0
263          Audi      A4  2014.0   48,000 km     6500000.0
312          Audi      A4  2014.0   48,000 km     6500000.0
2074         Audi      A4  2014.0   52,155 km     9200000.0
2132         Audi      A4  2014.0   52,155 km     9200000.0
6111         Audi      A4  2016.0   62,500 km     8950000.0
7411         Audi      A4  2016.0   62,500 km     8950000.0
2222         Audi      A4  2017.0  118,000 km     8000000.0
2275         Audi      A4  2017.0  118,000 km     8000000.0
7161         Audi      A4  2017.0   72,000 km     8800000.0
9474         Audi      A4  2017.0   72,000 km     8800000.0
1492         Audi      A4  2017.0   81,000 km     8900000.0
1537         Audi      A4  2017.0   81,000 km     8900000.0

In [11]:
car_specs=['manufacturer', 'variant', 'year', 'mileage', 'fuelType', 'transmission', 'engine']
near_duplicates=df[df.duplicated(subset=car_specs, keep=False)].sort_values(by=
    ['manufacturer', 'variant', 'year', 'mileage'])[car_specs+['listingPrice','name']].head(20)

near_duplicates

,manufacturer,variant,year,mileage,fuelType,transmission,engine,listingPrice,name
1935,Audi,A3,2018.0,"45,812 km",Petrol,Automatic,1200cc,8500000.0,Audi A3 2018 for sale in Karachi
2017,Audi,A3,2018.0,"45,812 km",Petrol,Automatic,1200cc,8500000.0,Audi A3 2018 for sale in Karachi
4840,Audi,A3,2018.0,"92,000 km",Petrol,Automatic,1200cc,6535000.0,Audi A3 2018 for sale in Karachi
4958,Audi,A3,2018.0,"92,000 km",Petrol,Automatic,1200cc,6535000.0,Audi A3 2018 for sale in Karachi
3843,Audi,A3,2019.0,"43,359 km",Petrol,Automatic,1200cc,6900000.0,Audi A3 2019 for sale in Karachi
3901,Audi,A3,2019.0,"43,359 km",Petrol,Automatic,1200cc,6900000.0,Audi A3 2019 for sale in Karachi
4630,Audi,A4,2012.0,"39,785 km",Petrol,Automatic,1800cc,7500000.0,Audi A4 2012 for sale in Karachi
4641,Audi,A4,2012.0,"39,785 km",Petrol,Automatic,1800cc,7500000.0,Audi A4 2012 for sale in Karachi
263,Audi,A4,2014.0,"48,000 km",Petrol,Automatic,1800cc,6500000.0,Audi A4 2014 for sale in Karachi
312,Audi,A4,2014.0,"48,000 km",Petrol,Automatic,1800cc,6500000.0,Audi A4 2014 for sale in Karachi
2074,Audi,A4,2014.0,"52,155 km",Petrol,Automatic,1800cc,9200000.0,Audi A4 2014 for sale in Karachi
2132,Audi,A4,2014.0,"52,155 km",Petrol,Automatic,1800cc,9200000.0,Audi A4 2014 for sale in Karachi
6111,Audi,A4,2016.0,"62,500 km",Petrol,Automatic,1400cc,8950000.0,Audi A4 2016 for sale in Karachi
7411,Audi,A4,2016.0,"62,500 km",Petrol,Automatic,1400cc,8950000.0,Audi A4 2016 for sale in Karachi
2222,Audi,A4,2017.0,"118,000 km",Petrol,Automatic,2000cc,8000000.0,Audi A4 2017 for sale in Karachi
2275,Audi,A4,2017.0,"118,000 km",Petrol,Automatic,2000cc,8000000.0,Audi A4 2017 for sale in Karachi
7161,Audi,A4,2017.0,"72,000 km",Petrol,Automatic,1400cc,8800000.0,Audi A4 2017 for sale in Karachi
9474,Audi,A4,2017.0,"72,000 km",Petrol,Automatic,1400cc,8800000.0,Audi A4 2017 for sale in Karachi
1492,Audi,A4,2017.0,"81,000 km",Petrol,Automatic,1400cc,8900000.0,Audi A4 2017 for sale in Karachi
1537,Audi,A4,2017.0,"81,000 km",Petrol,Automatic,1400cc,8900000.0,Audi A4 2017 for sale in Karachi

In [12]:
exact_dupes = df.duplicated(keep=False).sum()
near_dupes = df.duplicated(subset=car_specs, keep=False).sum()

print(f"Exact duplicates (all columns): {exact_dupes}")
print(f"Near duplicates (specs only): {near_dupes}")

Exact duplicates (all columns): 4911
Near duplicates (specs only): 6678

In [13]:
# Step 1: Ask Question 1 - "Who has identical car specs?"
near_dup_mask = df.duplicated(subset=car_specs, keep=False)

# Step 2: Ask Question 2 - "Who is a perfect clone?"
exact_dup_mask = df.duplicated(keep=False)

# Step 3: Combine  "Spec-twins that are NOT perfect clones"
final_mask = near_dup_mask & ~exact_dup_mask

# Step 4: Use the mask to filter the dataframe
df[final_mask].sort_values(
    by=['manufacturer', 'variant', 'year', 'mileage']
)[car_specs + ['listingPrice', 'name']].head(20)

,manufacturer,variant,year,mileage,fuelType,transmission,engine,listingPrice,name
11374,BYD,Atto 3,2025.0,1 km,Electric,Automatic,cc,9300000.0,BYD Atto 3 2025 for sale in Karachi
1231,Changan,Alsvin,2022.0,"35,000 km",Petrol,Automatic,1500cc,3800000.0,Changan Alsvin 2022 for sale in Karachi
8365,Changan,Alsvin,2022.0,"35,000 km",Petrol,Automatic,1500cc,3780000.0,Changan Alsvin 2022 for sale in Karachi
735,Changan,Alsvin,2025.0,10 km,Petrol,Automatic,1500cc,4649000.0,Changan Alsvin 2025 for sale in Karachi
9807,Changan,Alsvin,2025.0,10 km,Petrol,Automatic,1500cc,4799000.0,Changan Alsvin 2025 for sale in Karachi
14646,Changan,Karvaan,2019.0,"115,000 km",Petrol,Manual,1000cc,1800000.0,Changan Karvaan 2019 for sale in Karachi
14886,Changan,Karvaan,2019.0,"115,000 km",Petrol,Manual,1000cc,1975000.0,Changan Karvaan 2019 for sale in Karachi
10467,Changan,Karvaan,2021.0,"32,000 km",Petrol,Manual,1000cc,2330000.0,Changan Karvaan 2021 for sale in Karachi
10736,Changan,Karvaan,2021.0,"32,000 km",Petrol,Manual,1000cc,2550000.0,Changan Karvaan 2021 for sale in Karachi
13679,Changan,Oshan X7,2022.0,"38,000 km",Petrol,Automatic,1500cc,7500000.0,Changan Oshan X7 2022 for sale in Karachi
13802,Changan,Oshan X7,2022.0,"38,000 km",Petrol,Automatic,1500cc,7100000.0,Changan Oshan X7 2022 for sale in Karachi
5256,Changan,Oshan X7,2022.0,"56,000 km",Petrol,Automatic,1500cc,7480000.0,Changan Oshan X7 2022 for sale in Karachi
6345,Changan,Oshan X7,2022.0,"56,000 km",Petrol,Automatic,1500cc,7475000.0,Changan Oshan X7 2022 for sale in Karachi
1090,Changan,Oshan X7,2024.0,"25,000 km",Petrol,Automatic,1500cc,8450000.0,Changan Oshan X7 2024 for sale in Karachi
3932,Changan,Oshan X7,2024.0,"25,000 km",Petrol,Automatic,1500cc,8100000.0,Changan Oshan X7 2024 for sale in Karachi
2691,Changan,Oshan X7,2025.0,1 km,Petrol,Automatic,1500cc,8542000.0,Changan Oshan X7 2025 for sale in Karachi
13281,Changan,Oshan X7,2025.0,1 km,Petrol,Automatic,1500cc,9380000.0,Changan Oshan X7 2025 for sale in Karachi
3239,Changan,Oshan X7,2025.0,10 km,Petrol,Automatic,1500cc,8374000.0,Changan Oshan X7 2025 for sale in Karachi
3397,Changan,Oshan X7,2025.0,"18,000 km",Petrol,Automatic,1500cc,8175000.0,Changan Oshan X7 2025 for sale in Karachi
4312,Changan,Oshan X7,2025.0,19 km,Petrol,Automatic,1500cc,8041000.0,Changan Oshan X7 2025 for sale in Karachi

In [15]:
# Before cleaning
print(f"Original shape: {df.shape}")

# Drop duplicates based on car specs only (handles both exact AND near duplicates)
""" keep='first' does: For every group of rows with identical specs,
keep the one with the lowest original index and throw away the rest."""
df_clean = df.drop_duplicates(subset=car_specs, keep='first')

# After cleaning
print(f"Clean shape: {df_clean.shape}")
print(f"Rows dropped: {df.shape[0] - df_clean.shape[0]}")

Original shape: (15171, 10)
Clean shape: (11430, 10)
Rows dropped: 3741

In [16]:
# Same approach
print("First 20 unique mileages:")
print(df_clean['mileage'].unique()[:20])

print("\nMileage value counts tail:")
print(df_clean['mileage'].value_counts().tail(20))

First 20 unique mileages:
<StringArray>
['156,000 km',  '85,000 km',  '16,000 km',  '68,000 km',  '78,000 km',
  '18,000 km',  '34,000 km',  '10,000 km',  '54,000 km',  '12,000 km',
  '46,000 km', '104,730 km', '200,000 km', '120,000 km',  '44,500 km',
  '67,000 km',  '75,000 km',  '51,000 km',  '23,600 km',  '46,300 km']
Length: 20, dtype: str

Mileage value counts tail:
mileage
100,088 km    1
41,591 km     1
870,000 km    1
365,000 km    1
322,000 km    1
65,870 km     1
240,526 km    1
92,724 km     1
12,645 km     1
125,566 km    1
108,900 km    1
999,990 km    1
2,003 km      1
10,550 km     1
90,645 km     1
108,577 km    1
23,545 km     1
1,280 km      1
102,580 km    1
25,880 km     1
Name: count, dtype: int64